---
title: "Recomendación Fondo de Trend Following"
author: "riesgos"
date: "`r Sys.Date()`"
output:
  html_document:
    css: "style.css"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
library(readxl)
library(knitr)
library(kableExtra)
library(magrittr)
library(formattable)
```

```{r}
table <- read_excel('presentations/tables.xlsx', sheet = 'fondos_seleccionados')
table$AUM <- currency(table$AUM, digits = 0)
table$`Management Fee` <- percent(table$`Management Fee`,digits = 1)
table$`Performance Fee` <- percent(table$`Performance Fee`,digits = 0)
kable(table)  %>% kable_classic()
```


```{r}
table <- read_excel('presentations/tables.xlsx', sheet = 'pros-cons')
table
table[is.na(table)] <- ' '
kable(table[1:3,])  %>% kable_classic()
kable(table[5:8,])  %>% kable_classic()
```
```{r}
library(tidyr)
library(dplyr)
table <- read_excel('presentations/tables.xlsx', sheet = 'MAR_Ranking', na = "HOLA") %>%
  pivot_longer(-Manager) %>% mutate(value = as.character(value)) %>%
  mutate(value = ifelse(is.na(value)," ",value))

table <- table %>% pivot_wider(names_from = name,values_from = value)
library(formattable)
formattable(table, list(area(col = 2:23) ~ color_tile("green", "blue")))
kable(table)  %>% kable_classic_2(, html_font = 'eb garamond')
```
